config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "projects#index"

  resources :projects do
    resources :tickets
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id          :bigint           not null, primary key
#  name        :string           not null
#  description :text
#
class Project < ApplicationRecord
  self.table_name = "projects"
  validates_presence_of :name
  validates_uniqueness_of :name
  has_many :tickets
end

app/models/ticket.rb
# == Schema Information
#
# Table name: tickets
#
#  id          :bigint           not null, primary key
#  name        :string           not null
#  description :text             not null
#  priority    :integer          default(1), not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  project_id  :integer          not null
#  status      :integer          default(0)
#
class Ticket < ApplicationRecord
  self.table_name = "tickets"

  module CONST
    LOW = "Low".freeze
    MEDIUM = "Medium".freeze
    HIGH = "High".freeze

    PRIORITIES = {
      1 => LOW,
      3 => MEDIUM,
      5 => HIGH
    }.freeze

    NEW = "New".freeze
    IN_PROGRESS = "In Progress".freeze
    FINISHED = "Finished".freeze

    STATUSES = {
      0 => NEW,
      3 => IN_PROGRESS,
      5 => FINISHED
    }.freeze
  end

  validates_presence_of :name, :priority
  validates_inclusion_of :priority, { in: CONST::PRIORITIES.keys }

  belongs_to :project

  def priority_label
    CONST::PRIORITIES[self.priority]
  end

  def status_label
    CONST::STATUSES[self.status]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    if Project.none?
      redirect_to new_project_path
    else
      @projects = Project.all
    end
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.save ? (redirect_to projects_path) : (render new_project_path)
  end

  def show
    @project = Project.find(params[:id])
    @tickets = @project.tickets
  end

  private

  def project_params
    params.require(:project).permit(:id, :name, :description)
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def index
    @project = Project.find(params[:project_id])
    @tickets = @project.tickets
  end

  def new
    @ticket = Ticket.new(new_ticket_params)
  end

  def create
    @ticket = Ticket.create(create_ticket_params)
    redirect_to project_tickets_path(@ticket.project)
  end

  def show
    @ticket = Ticket.find(params[:id])
  end

  def edit
    @ticket = Ticket.find(params[:id])
  end

  def update
    @ticket = Ticket.find(params[:id])
    if @ticket.update(update_ticket_params)
      redirect_to project_ticket_path(@ticket.project, @ticket)
    else
      render "edit"
    end
  end

  private

  def new_ticket_params
    params.permit(:project_id)
  end

  def create_ticket_params
    params.require(:ticket).permit(:name, :description, :priority, :status, :done, :project_id)
  end

  def update_ticket_params
    params.require(:ticket).permit(:name, :description, :priority, :status, :done)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Railtrack" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= yield :head %>
    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>
  <body>
    <div class="top-header">
      Railtrack project
    </div>
    <br>
    <%= yield %>
  </body>
</html>

app/views/projects/index.html.erb
<div class="index-main">
  <% @projects.each do |project| %>
    <div class="project-box">
      <%= link_to project.name, project_path(project) %>
      <div>
        <%= project.description %>
      </div>
      <br>
      <div>
        <%= link_to 'Create new ticket', new_project_ticket_path(project) %>
      </div>
    </div>
  <% end %>
</div>
<div>
  <%= link_to 'Create new project', new_project_path, class: 'new-project-link' %>
</div>

app/views/projects/new.html.erb
<%= form_with model: @project do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>
  <%= form.submit %>
<% end %>

app/views/projects/show.html.erb
<table class="content-table">
  <h3><%= @project.name %> tickets</h3>
  <thead>
    <tr>
      <th>Name</th>
      <th>Priority</th>
      <th>Status</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= link_to(ticket.name, project_ticket_path(@project, ticket)) %></td>
        <td><%= ticket.priority_label %></td>
        <td><%= ticket.status_label %></td>
        <td><%= link_to('edit', edit_project_ticket_path(@project, ticket)) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div>
  <%= link_to 'Create new ticket', new_project_ticket_path(@project) %>
</div>

app/views/tickets/edit.html.erb
<br>
<%= form_with model: @ticket, url: { action: "update" } do |form| %>
  <div>
    <%= form.text_field(:name, class: 'ticket-input-field', placeholder: 'Name') %>
  </div>
  <div>
    <%= form.text_area(:description, class: 'ticket-input-field ticket-input-description-field', placeholder: 'Description') %>
  </div>
  <div>
    <%= form.select :priority, Ticket::CONST::PRIORITIES.invert.to_a %>
  </div>
  <div>
    <%= form.select :status, Ticket::CONST::STATUSES.invert.to_a %>
  </div>
  <%= form.hidden_field :project_id, value: @ticket.project_id %>
  <div>
    <%= form.submit(:'Update Ticket', class: 'ticket-update-button') %>
  </div>
<% end %>

app/views/tickets/index.html.erb
<table class="content-table">
  <h3><%= @project.name %> tickets</h3>
  <thead>
  <tr>
    <th>Name</th>
    <th>Priority</th>
    <th>Status</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @tickets.each do |ticket| %>
    <tr>
      <td><%= link_to(ticket.name, project_ticket_path(@project, ticket)) %></td>
      <td><%= ticket.priority_label %></td>
      <td><%= ticket.status_label %></td>
      <td><%= link_to('edit', edit_project_ticket_path(@project, ticket)) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<div>
  <%= link_to 'Create new ticket', new_project_ticket_path(@project) %>
</div>

app/views/tickets/new.html.erb
<br>
<%= form_with model: @ticket, url: { action: "create" } do |form| %>
  <div>
    <%= form.text_field(:name, class: 'ticket-input-field', placeholder: 'Name') %>
  </div>
  <div>
    <%= form.text_area(:description, class: 'ticket-input-field ticket-input-description-field', placeholder: 'Description') %>
  </div>
  <div>
    <%= form.select :priority, Ticket::CONST::PRIORITIES.invert.to_a %>
  </div>
  <div>
    <%= form.select :status, Ticket::CONST::STATUSES.invert.to_a %>
  </div>
  <%= form.hidden_field :project_id, value: @ticket.project_id %>
  <div>
    <%= form.submit(:'Create Ticket', class: 'ticket-create-button') %>
  </div>
<% end %>

app/views/tickets/show.html.erb
<table class="content-table">
  <thead>
  </thead>
  <tbody>
    <tr>
      <td><%= @ticket.name %></td>
    </tr>
    <tr>
      <td><%= @ticket.description %></td>
    </tr>
    <tr>
      <td><%= @ticket.priority_label %></td>
    </tr>
    <tr>
      <td><%= @ticket.status_label %></td>
    </tr>
    <tr>
      <td><%= link_to('edit', edit_project_ticket_path(@ticket.project, @ticket)) %></td>
    </tr>
  </tbody>
</table>

<%= link_to 'Back', project_path(@ticket.project) %>